# Generated by Django 4.1 on 2022-08-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_alternative_part_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
