# Generated by Django 4.1 on 2022-08-20 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventory_aircraft_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='aircraft_type',
            field=models.ManyToManyField(blank=True, null=True, to='inventory.aircrafttype'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.manufacturer'),
        ),
    ]
