# Generated by Django 4.1 on 2022-08-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventory_aircraft_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='aircraft_type',
            field=models.ManyToManyField(blank=True, to='inventory.aircrafttype'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='descriptions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
